version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: mysql-desafio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bBK879@@
      MYSQL_DATABASE: desafio
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./docker/dbDesafio.sql:/docker-entrypoint-initdb.d/1dbDesafio.sql"
      - "./docker/insertUsers.sql:/docker-entrypoint-initdb.d/2insertUsers.sql"
      - "./docker/insertSilvers.sql:/docker-entrypoint-initdb.d/3insertSilvers.sql"
      - "./docker/insertLoneliness.sql:/docker-entrypoint-initdb.d/4insertLoneliness.sql"
      - "./docker/insertResources.sql:/docker-entrypoint-initdb.d/5insertResources.sql"
    networks:
      - desafio
  node:
    build: ./backend
    container_name: node-desafio
    restart: always
    environment:
      - VIRTUAL_HOST=api.batera.vickypr.es
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.batera.vickypr.es
      - LETSENCRYPT_EMAIL=admin@vickypr.es
    expose:
      - 3000
    depends_on:
      - mysql
    networks:
      - desafio
      - proxy
    volumes:
      - ./backend:/usr/src/app
      - exclude:/usr/src/app/node_modules/
  react:
    image: nginx:alpine
    container_name: react-desafio
    restart: always
    environment:
      - VIRTUAL_HOST=batera.vickypr.es
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=batera.vickypr.es
      - LETSENCRYPT_EMAIL=admin@vickypr.es
    expose:
      - 80
    depends_on:
      - node
    networks:
      - egames
      - proxy
    volumes:
      - /home/ubuntu/batera:/usr/share/nginx/html:ro
volumes:
  exclude:
networks:
  desafio:
  proxy:
    name: nginx-proxy
    external: true
